name: .NET-Console-App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run a sample
        run: echo GitDemo

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
              dotnet-version: '4.8.1'
              
      - name: Build
        run: |
              dotnet restore
              dotnet build --configuration Release
              dotnet publish -c Release
              
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ${{ github.workspace }}/bin/Release/
            ${{ github.workspace }}/publish/
          retention-days: 7
      