name: GitDemo

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Build
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release
              
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ${{ github.workspace }}/bin/Release/
            ${{ github.workspace }}/publish/
          retention-days: 7